### PR TITLE
Update TW_Dialog.txt

### PR DESCRIPTION
**Pull request by WayTooCynical**
DO NOT MERGE - still cleaning up prologue dialogue orders but wanted to grab a bite to eat

### CODE REVIEW

**Comment by haWesley** [comment]
i hope you enjoyed your food

**Comment by WayTooCynical** [comment]
Ahhhh crap I completely forgot to follow up. Will finish the strand later
tonight after work

**Comment by haWesley** [comment]
haha, no worries!

**Comment by KatsuragiYusa** [comment]
will wait for this

**Comment by haWesley** [comment]
let me know when this is good for merging by the way!

**Comment by haWesley** [comment]
Any updates on this being good for merging? I just want to verify before I touch anything,

**Comment by WayTooCynical** [comment]
Just waiting on Mccs to look through it, but otherwise it's completed up to
first encounter with ruffel

**Pull request closed without merging**
